=== samplex191-boop/lab_8/students.dtd
<!ELEMENT students (student+)>
<!ATTLIST students
  xmlns:xsi CDATA #IMPLIED
  xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT student (name, age, course)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== samplex191-boop/lab_8/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="students.xsd">
  <student>
    <name>John Doe</name>
    <age>22</age>
    <course>Computer Science</course>
  </student>
  <student>
    <name>Jane Smith</name>
    <age>21</age>
    <course>Information Technology</course>
  </student>
  <student>
    <name>Michael Lee</name>
    <age>23</age>
    <course>Software Engineering</course>
  </student>
</students>
